nodeLinker: node-modules

enableGlobalCache: false

compressionLevel: mixed

httpTimeout: 300000

yarnPath: .yarn/releases/yarn-4.12.0.cjs

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
    - arm64
    - s390x
    - ppc64
