FROM docker.io/library/node:22.17 AS builder

ARG PLUGIN=odf
ARG OPENSHIFT_CI=true

ENV OPENSHIFT_CI=${OPENSHIFT_CI}

WORKDIR /app

COPY . /app

RUN node .yarn/releases/yarn-4.12.0.cjs workspaces focus --all --production
RUN BUILD_SCRIPT=build; \
    if [ "$PLUGIN" = "client" ]; then \
      BUILD_SCRIPT="${BUILD_SCRIPT}-client"; \
    elif [ "$PLUGIN" = "mco" ]; then \
      BUILD_SCRIPT="${BUILD_SCRIPT}-mco"; \
    fi && \
    NODE_OPTIONS="--max-old-space-size=1024" node .yarn/releases/yarn-4.12.0.cjs "${BUILD_SCRIPT}" && \
    mv /app/plugins/${PLUGIN}/dist /dist

FROM registry.access.redhat.com/ubi9/nginx-120

COPY --from=builder /dist /opt/app-root/src
COPY --from=builder /dist /opt/app-root/src/compatibility

USER root
RUN ln -sf /opt/app-root/etc/nginx.d/nginx.conf /etc/nginx/nginx.conf
USER default

CMD ["/usr/libexec/s2i/run"]
