FROM quay.io/coreos/tectonic-console-builder:v24
ENV NODE_VERSION="v14.17.3"
RUN cd /tmp \
  && wget --quiet -O /tmp/node.tar.gz http://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.gz \
  && tar xf node.tar.gz && rm -f /tmp/node.tar.gz && cd node-* && cp -r lib/node_modules /usr/local/lib/node_modules \
  && cp bin/node /usr/local/bin && ln -sf /usr/local/lib/node_modules/npm/bin/npm-cli.js /usr/local/bin/npm
RUN chmod 777 /usr/local/lib/node_modules
RUN rm -rf /tmp/node-v*
