FROM docker.io/library/node:18.12.1 AS builder
WORKDIR /app
COPY . /app
RUN yarn install --prod --frozen-lockfile
RUN NODE_OPTIONS="--max-old-space-size=1024" yarn build

FROM nginxinc/nginx-unprivileged:1.20.1
WORKDIR /opt/app-root/src
COPY --from=builder /app/plugins/odf/dist .
COPY --from=builder /app/plugins/odf/dist ./compatibility
ENTRYPOINT ["nginx", "-g", "daemon off;"]
